# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Ensure bind-mount directories exist for containers.
  systemd.tmpfiles.rules = lib.mkAfter [
    # MongoDB data/config on host under /var/lib (standard FHS location).
    "d /var/lib/mongodb 0755 root root - -"
    "d /var/lib/mongodb/config 0777 root root - -"
    "d /var/lib/mongodb/data 0777 root root - -"

    # Neo4j data (disabled for now)
    "d /var/lib/neo4j 0755 root root - -"
    "d /var/lib/neo4j/data 0777 root root - -"
    "d /var/lib/neo4j/logs 0777 root root - -"
    "d /var/lib/neo4j/plugins 0777 root root - -"

    # Postgres data
    "d /var/lib/postgresql 0755 root root - -"
  ];

  # Containers
  # NOTE: MongoDB enabled; keep auth simple for now.
  # Recommended: wire credentials via `environmentFiles` + sops.
  virtualisation.oci-containers.containers."mongodb" = {
    image = "mongo:latest";
    environment = { };
    volumes = [
      "/var/lib/mongodb/config:/data/configdb:rw"
      "/var/lib/mongodb/data:/data/db:rw"
    ];
    ports = [
      "27017:27017/tcp"
    ];
    "log-driver" = "journald";
    extraOptions = [
      "--network-alias=mongodb"
      "--network=comparator_default"
    ];
  };
  systemd.services."podman-mongodb" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-comparator_default.service"
    ];
    requires = [
      "podman-network-comparator_default.service"
    ];
    partOf = [
      "podman-compose-comparator-root.target"
    ];
    wantedBy = [
      "podman-compose-comparator-root.target"
    ];
  };

  virtualisation.oci-containers.containers."neo4j" = {
    image = "neo4j:latest";
    environment = {
      # Temporary: no auth during bring-up.
      "NEO4J_AUTH" = "none";
      "NEO4J_PLUGINS" = "[\"apoc\"]";
    };
    volumes = [
      "/var/lib/neo4j/data:/data:rw"
      "/var/lib/neo4j/logs:/logs:rw"
      "/var/lib/neo4j/plugins:/plugins:rw"
    ];
    ports = [
      "7687:7687/tcp"
      "7474:7474/tcp"
    ];
    "log-driver" = "journald";
    extraOptions = [
      "--network-alias=neo4j"
      "--network=comparator_default"
    ];
  };
  systemd.services."podman-neo4j" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-comparator_default.service"
    ];
    requires = [
      "podman-network-comparator_default.service"
    ];
    partOf = [
      "podman-compose-comparator-root.target"
    ];
    wantedBy = [
      "podman-compose-comparator-root.target"
    ];
  };

  virtualisation.oci-containers.containers."postgres" = {
    image = "postgres:18";

    # NOTE: This is intentionally using "trust" for local bring-up.
    # Recommended: remove "POSTGRES_HOST_AUTH_METHOD" and use a real password via
    # `environmentFiles = [ config.sops.secrets.<name>.path ];` (or another .env file).
    environment = {
      "POSTGRES_DB" = "myappdb";
      "POSTGRES_HOST_AUTH_METHOD" = "trust";
      "POSTGRES_USER" = "admin";
    };
    # Postgres 18+ expects a single mount at /var/lib/postgresql
    # (it stores data in a versioned subdirectory).
    volumes = [
      "/var/lib/postgresql:/var/lib/postgresql:rw"
    ];
    ports = [
      "5432:5432/tcp"
    ];
    "log-driver" = "journald";
    extraOptions = [
      "--network-alias=postgres"
      "--network=comparator_default"
    ];
  };
  systemd.services."podman-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-comparator_default.service"
    ];
    requires = [
      "podman-network-comparator_default.service"
    ];
    partOf = [
      "podman-compose-comparator-root.target"
    ];
    wantedBy = [
      "podman-compose-comparator-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-comparator_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f comparator_default";
    };
    script = ''
      podman network inspect comparator_default || podman network create comparator_default
    '';
    partOf = [ "podman-compose-comparator-root.target" ];
    wantedBy = [ "podman-compose-comparator-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-comparator-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
