# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."mongodb" = {
    image = "mongo:latest";
    environment = {
      "MONGO_INITDB_ROOT_PASSWORD" = "";
      "MONGO_INITDB_ROOT_USERNAME" = "admin";
    };
    volumes = [
      "/data/drive/comparator/mongodb/config:/data/configdb:rw"
      "/data/drive/comparator/mongodb/data:/data/db:rw"
    ];
    ports = [
      "27017:27017/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mongodb"
      "--network=comparator_default"
    ];
  };
  systemd.services."podman-mongodb" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-comparator_default.service"
    ];
    requires = [
      "podman-network-comparator_default.service"
    ];
    partOf = [
      "podman-compose-comparator-root.target"
    ];
    wantedBy = [
      "podman-compose-comparator-root.target"
    ];
  };
  virtualisation.oci-containers.containers."neo4j" = {
    image = "neo4j:latest";
    environment = {
      "NEO4J_AUTH" = "neo4j/";
      "NEO4J_PLUGINS" = "[\"apoc\"]";
    };
    volumes = [
      "/data/drive/comparator/neo4j/data:/data:rw"
      "/data/drive/comparator/neo4j/logs:/logs:rw"
      "/data/drive/comparator/neo4j/plugins:/plugins:rw"
    ];
    ports = [
      "7687:7687/tcp"
      "3000:7474/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=neo4j"
      "--network=comparator_default"
    ];
  };
  systemd.services."podman-neo4j" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-comparator_default.service"
    ];
    requires = [
      "podman-network-comparator_default.service"
    ];
    partOf = [
      "podman-compose-comparator-root.target"
    ];
    wantedBy = [
      "podman-compose-comparator-root.target"
    ];
  };
  virtualisation.oci-containers.containers."postgres" = {
    image = "postgres:18";
    environment = {
      "POSTGRES_DB" = "myappdb";
      "POSTGRES_PASSWORD" = "";
      "POSTGRES_USER" = "admin";
    };
    volumes = [
      "/data/drive/comparator/postgres:/var/lib/postgresql/data:rw"
    ];
    ports = [
      "5432:5432/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=postgres"
      "--network=comparator_default"
    ];
  };
  systemd.services."podman-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-comparator_default.service"
    ];
    requires = [
      "podman-network-comparator_default.service"
    ];
    partOf = [
      "podman-compose-comparator-root.target"
    ];
    wantedBy = [
      "podman-compose-comparator-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-comparator_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f comparator_default";
    };
    script = ''
      podman network inspect comparator_default || podman network create comparator_default
    '';
    partOf = [ "podman-compose-comparator-root.target" ];
    wantedBy = [ "podman-compose-comparator-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-comparator-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
