import json
import pandas as pd
import os

from prefect import flow
from prefect.artifacts import create_table_artifact, create_markdown_artifact
from prefect_aws import AwsCredentials
from prefect_aws.s3 import S3Bucket

# --- Configuration ---
# The file generated by your find_similarities.py script
# GENERATED_MATCHES_FILE = 'input/rawreport.json'

# The manually created CSV file with correct matches.
# GROUND_TRUTH_FILE = 'ground_truth.csv' 

# The new CSV file that will contain the detailed error analysis.
# DETAILED_REPORT_FILE = 'evaluation_details.csv'

# --- Column Names in your Ground Truth CSV file ---
# *** YOU MUST UPDATE THESE TO MATCH YOUR CSV FILE ***
# The script will use these columns to read IDs and product names.
EROSKI_ID_COLUMN = 'ER Referencia eroski'
MAKRO_ID_COLUMN = 'Ref competidor'

# Add product name columns to your ground truth file for a more informative report.
# If these columns don't exist, the report will still work, but these fields will be blank.
EROSKI_DENOMINATION_COLUMN = 'Eroski_Denomination'
MAKRO_DENOMINATION_COLUMN = 'Makro_Denomination'


@flow(name="evaluate_matches")
def evaluate_matches(execution_id: str, input_filename: str, output_filename: str):
    """
    Main function to run the complete evaluation and generate reports.
    """

    s3bucket = S3Bucket.load("s3-report")
    static_s3bucket = S3Bucket.load("s3-report-static")

    # NOTE: read rawreport.json from s3
    # The file generated by your find_similarities.py script
    # Shoudn't it be report.json instead?
    raw_similarities_report = s3bucket.read_path(path=input_filename)
    similarities_report: list[dict] = json.loads(raw_similarities_report)
    generated_matches = load_generated_matches(similarities_report)

    # truth_report = static_s3bucket.read_path(path="ground_truth.csv")
    truth_rawpath = static_s3bucket.download_folder_to_path(
        from_folder="./",
        to_folder="./"
    )
    truth_filepath = str(truth_rawpath / "ground_truth.csv")
    truth_matches = load_ground_truth_matches(truth_filepath)

    if not generated_matches or not truth_matches:
        print("Evaluation could not be completed due to errors loading files.")
        return

    # Create sets of the ID pairs for metric calculations
    generated_keys = set(generated_matches.keys())
    truth_keys = set(truth_matches.keys())

    # --- Calculate Metrics ---
    true_positives = generated_keys.intersection(truth_keys)
    false_positives = generated_keys - truth_keys
    false_negatives = truth_keys - generated_keys

    num_correct = len(true_positives)
    num_generated = len(generated_keys)
    num_truth = len(truth_keys)

    precision = num_correct / num_generated if num_generated > 0 else 0.0
    recall = num_correct / num_truth if num_truth > 0 else 0.0
    f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0

    general_report = {
        "matches_found_by_similarities": num_generated,
        "total_truth_matches": num_truth,
        "total_common_matches": num_correct,
        "total_new_match_or_false_positive": len(false_positives),
        "total_missed_matches_from_truth": len(false_negatives),
        "precision": f"{precision:.2%}",
        "recall": f"{recall:.2%}",
        "f1_score": f"{f1_score:.2%}"
    }

    str_general_report = json.dumps(general_report, indent=2)

    markdown_report = f"""```python
       {str_general_report}
    """
    create_markdown_artifact(
        key="general-report",
        markdown=markdown_report,
        description="Evaluate matches general report"

    )

    # --- Print Report ---
    print("\n--- Match Evaluation Report ---")

    # Total number of matches results of tokenizer.py + find_similarities.py
    print(f"Total Matches Found by Similarities: {num_generated}")

    # Total number of matches on the last monthly report used as truth
    print(f"Total Truth Matches (last report): {num_truth}")

    # Common repeated matches between last and this month reports
    print(f"Correctly Identified Matches (common): {num_correct}")

    # New matches that weren't found on last report.
    # This section may contain new true matches or false positive matches that don't relate directly.
    print(f"Similarities new match or false positive (review): {len(false_positives)}.")

    # Last report good matches that weren't found on current report
    print(f"Last report with NO current match (missed): {len(false_negatives)}.")

    print("---------------------------------")
    print(f"Precision: {precision:.2%}")
    print(f"Recall:    {recall:.2%}")
    print(f"F1-Score:  {f1_score:.2%}")
    print("---------------------------------")

    # --- Generate Detailed CSV Report ---
    detailed_report: list[dict] = generate_detailed_report(true_positives, false_positives, false_negatives, generated_matches, truth_matches)

    # Create DataFrame and save to CSV
    report_df = pd.DataFrame(detailed_report)
    try:
        report_df.to_csv(output_filename, index=False, encoding='utf-8')
        print(f"\nSaved detailed report with {len(true_positives)} correct matches, {len(false_positives)} potential new/incorrect matches,")
        print(f"and {len(false_negatives)} missed matches to '{output_filename}'.")
    except Exception as e:
        print(f"An error occurred while saving the detailed report: {e}")

    matches_report = report_df.to_dict(orient="records")
    _ = create_table_artifact(
        key="detailed-report",
        table=matches_report,
        description="Evaluate matches detailed report")

    s3bucket.upload_from_path(from_path=output_filename, to_path=output_filename)


def load_generated_matches(data: list[dict]) -> dict:
    """
    Loads the matches from the JSON report and stores them in a dictionary
    for easy lookup, mapping pairs to their detailed data.

    :param file_path: Path to the raw_report.json file.
    :return: A dictionary where keys are (eroski_id, makro_id) tuples and
             values are the detailed match data.
    """

    generated_matches_dict = {}
    for item in data:
        if 'id' in item and 'similar_products' in item and item['similar_products']:
            eroski_id = str(item['id'])
            makro_match = item['similar_products'][0]
            makro_id = str(makro_match['id'])

            # Store all relevant info for reporting
            match_details = {
                'eroski_denomination': item.get('description', 'N/A'),
                'distance': makro_match.get('distance', 999),
                'makro_denomination': makro_match.get('denomination', 'N/A'),
            }
            generated_matches_dict[(eroski_id, makro_id)] = match_details

    return generated_matches_dict


def load_ground_truth_matches(file_path: str) -> dict:
    """
    Loads the manually verified matches from a CSV file into a dictionary.

    :param file_path: Path to the ground_truth.csv file.
    :return: A dictionary where keys are (eroski_id, makro_id) tuples and
             values are the product denominations.
    """
    if not os.path.exists(file_path):
        print(f"[ERROR] Ground truth file not found at: {file_path}")
        return {}

    try:
        # Define column types to avoid issues with numbers being read as floats
        dtype_map = {EROSKI_ID_COLUMN: str, MAKRO_ID_COLUMN: str}
        # FIX
        df = pd.read_csv(file_path, dtype=dtype_map)

        # Ensure the required ID columns exist
        if EROSKI_ID_COLUMN not in df.columns or MAKRO_ID_COLUMN not in df.columns:
            print(f"[ERROR] Ground truth file must contain columns '{EROSKI_ID_COLUMN}' and '{MAKRO_ID_COLUMN}'.")
            return {}

        df.dropna(subset=[EROSKI_ID_COLUMN, MAKRO_ID_COLUMN], inplace=True)
        
        truth_matches_dict = {}
        for _, row in df.iterrows():
            eroski_id = row[EROSKI_ID_COLUMN]
            makro_id = row[MAKRO_ID_COLUMN]
            
            # Get denominations if columns exist, otherwise use 'N/A'
            eroski_denom = row.get(EROSKI_DENOMINATION_COLUMN, 'N/A')
            makro_denom = row.get(MAKRO_DENOMINATION_COLUMN, 'N/A')
            
            truth_matches_dict[(eroski_id, makro_id)] = {
                'eroski_denomination': eroski_denom,
                'makro_denomination': makro_denom
            }
        return truth_matches_dict

    except Exception as e:
        print(f"An error occurred while reading the CSV file: {e}")
        return {}


def generate_detailed_report(true_positives, false_positives, false_negatives, generated_data, truth_data) -> list:
    """
    Creates a single CSV report containing both false positives and false negatives,
    including product details for easy analysis.

    :param false_positives: A set of (eroski_id, makro_id) pairs the script found incorrectly.
    :param false_negatives: A set of (eroski_id, makro_id) pairs the script missed.
    :param generated_data: The full dictionary of generated matches.
    :param truth_data: The full dictionary of ground truth matches.
    """
    report_data = []

    # Process True Positives
    for eroski_id, makro_id in sorted(list(true_positives), key=lambda x: generated_data[x]['distance']):
        details = generated_data[(eroski_id, makro_id)]
        report_data.append({
            'Match_Type': 'True Positive',
            'Eroski_ID': eroski_id,
            'Eroski_Denomination': details['eroski_denomination'],
            'Makro_ID': makro_id,
            'Makro_Denomination': details['makro_denomination'],
            'Similarity_Distance': details['distance']
        })

    # Process False Positives
    for eroski_id, makro_id in sorted(list(false_positives), key=lambda x: generated_data[x]['distance']):
        details = generated_data[(eroski_id, makro_id)]
        report_data.append({
            'Error_Type': 'False Positive',
            'Eroski_ID': eroski_id,
            'Eroski_Denomination': details['eroski_denomination'],
            'Makro_ID': makro_id,
            'Makro_Denomination': details['makro_denomination'],
            'Similarity_Distance': details['distance']
        })

    # Process False Negatives
    for eroski_id, makro_id in sorted(list(false_negatives)):
        details = truth_data[(eroski_id, makro_id)]
        report_data.append({
            'Error_Type': 'False Negative',
            'Eroski_ID': eroski_id,
            'Eroski_Denomination': details['eroski_denomination'],
            'Makro_ID': makro_id,
            'Makro_Denomination': details['makro_denomination'],
            'Similarity_Distance': 'N/A' # No distance available for missed matches
        })
    
    if not report_data:
        print("No discrepancies found to report.")
        return []

    return report_data


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Run or deploy the Eroski scrape workflow.")
    parser.add_argument(
        "--version",
        type=str,
        default="default",
        help="Specify the version for deployment or local execution (e.g., 'v1', 'v2', 'main')."
    )
    parser.add_argument(
        "--deploy",
        action="store_true",
        help="Deploy the workflow to Prefect."
    )
    args = parser.parse_args()
    if args.deploy:
        # --- Prefect deployment logic ---
        print("Deploying evaluate matches flow to Prefect...")
        evaluate_matches.deploy(
            name=args.version,
            version=args.version,
            tags=["evaluate", "matches"],
            work_pool_name=args.version,
            image=f"990187902980.dkr.ecr.us-east-1.amazonaws.com/report:{args.version}_evaluate_matches",
            build=True,
            push=True
        )
        print("Deployment command executed. Check your Prefect UI for status.")

    else:
        # --- Local execution logic ---
        print("Running evaluate matches flow locally...")

        # NOTE: this process depends on the static file ground_truth.csv and the dynamic input file stored within s3
        # rawreport.json, this means we will probably set execution id manually for testing.

        # TEST: Manual execution id for testing
        execution_id = "202508141755214580"

        # --- Create and save S3 bucket block ---
        s3bucket = S3Bucket(
            bucket_name="comexsoft-workflows",
            bucket_folder=f"report/{execution_id}",
            credentials=AwsCredentials.load("credentials")  # type: ignore
        )

        # NOTE: Need to overwrite for using the local execution id and avoid init error
        s3block = s3bucket.save("s3-report", overwrite=True)
        s3block = s3bucket.save("s3-report-static", overwrite=True)

        evaluate_matches(
            execution_id=execution_id,
            input_filename="rawreport.json",
            output_filename="evaluation_details.csv"
        )
