"""
Web interface for validating product matches from PostgreSQL.

This application provides a user-friendly interface to review and validate
product matches that were generated by the similarity analysis pipeline.

Usage:
    python validate_web.py [--port 5000] [--host 0.0.0.0]
"""

from flask import Flask, render_template, request, jsonify
import psycopg2
from psycopg2.extras import RealDictCursor
import logging
import sys
from pathlib import Path
from datetime import datetime

# Add project root to path
project_root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(project_root))

from config.settings import POSTGRES_DB_CONFIG

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)-8s | %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)

app = Flask(__name__)

def get_db_connection():
    """Create and return a PostgreSQL database connection."""
    try:
        conn = psycopg2.connect(
            host=POSTGRES_DB_CONFIG['host'],
            port=POSTGRES_DB_CONFIG['port'],
            database=POSTGRES_DB_CONFIG['database'],
            user=POSTGRES_DB_CONFIG['user'],
            password=POSTGRES_DB_CONFIG['password'],
            cursor_factory=RealDictCursor
        )
        return conn
    except psycopg2.Error as e:
        logger.error(f"Database connection error: {e}")
        raise

@app.route('/')
def index():
    """Main page showing validation interface."""
    return render_template('validate_matches.html')

@app.route('/api/matches')
def get_matches():
    """
    Get matches for validation.
    
    Query parameters:
        - status: 'pending', 'validated', 'all' (default: 'pending')
        - validation_result: filter by validation_result ('perfect', 'correct', 'incorrect', 'uncertain')
        - limit: number of records to return (default: 50)
        - offset: pagination offset (default: 0)
        - min_score: minimum combined_score filter (optional)
        - store_a: filter by store_a (optional)
        - store_b: filter by store_b (optional)
        - product_a_id: filter by specific product_a_id (optional)
    
    Returns matches with priority:
        1. Perfect match if exists
        2. Most recent validated match (correct/incorrect/uncertain) if exists
        3. If there's another match with higher score, include it as 'recommended_match'
    """
    status = request.args.get('status', 'pending')
    validation_result_filter = request.args.get('validation_result')
    limit = int(request.args.get('limit', 50))
    offset = int(request.args.get('offset', 0))
    min_score = request.args.get('min_score', type=float)
    store_a = request.args.get('store_a')
    store_b = request.args.get('store_b')
    product_a_id = request.args.get('product_a_id')
    product_name = request.args.get('product_name')
    
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        
        # Build query to get ALL matches grouped by product_a_id
        # Each product will have all its matches as alternative options
        query = """
        SELECT 
            id,
            product_a_id,
            product_a_siid,
            product_a_name,
            product_a_description,
            product_a_url,
            store_a,
            product_b_id,
            product_b_siid,
            product_b_name,
            product_b_description,
            product_b_url,
            store_b,
            graph_score,
            name_similarity,
            description_similarity,
            euclidean_similarity,
            combined_score,
            overlap_count,
            shared_nodes,
            created_at,
            validated,
            validation_result,
            notes,
            previous_validation_result,
            previous_validation_date,
            CASE 
                WHEN validation_result = 'perfect' THEN 1
                WHEN validated = TRUE THEN 2
                ELSE 3
            END as priority_order
        FROM product_match_validation
        WHERE 1=1
        """
        
        params = []
        
        # Status filter
        if status == 'pending':
            query += " AND (validated = FALSE OR validated IS NULL)"
        elif status == 'validated':
            query += " AND validated = TRUE"
        
        # Validation result filter
        if validation_result_filter:
            query += " AND validation_result = %s"
            params.append(validation_result_filter)
        
        # Score filter
        if min_score is not None:
            query += " AND combined_score >= %s"
            params.append(min_score)
        
        # Store filters
        if store_a:
            query += " AND store_a = %s"
            params.append(store_a)
        
        if store_b:
            query += " AND store_b = %s"
            params.append(store_b)
        
        # Product filter
        if product_a_id:
            query += " AND product_a_id = %s"
            params.append(product_a_id)
        
        # Product name filter (search in product_a_name or product_b_name)
        if product_name:
            query += " AND (LOWER(product_a_name) LIKE LOWER(%s) OR LOWER(product_b_name) LIKE LOWER(%s))"
            search_pattern = f"%{product_name}%"
            params.append(search_pattern)
            params.append(search_pattern)
        
        query += """
        ORDER BY product_a_id, store_b, priority_order, combined_score DESC, created_at DESC
        """
        
        cursor.execute(query, params)
        all_matches = cursor.fetchall()
        
        # Group matches by (product_a_id, store_b)
        from collections import defaultdict
        grouped_matches = defaultdict(list)
        
        for match in all_matches:
            key = (match['product_a_id'], match['store_b'])
            grouped_matches[key].append(match)
        
        # Convert to list of product groups with all their matches
        matches = []
        for (product_a_id, store_b), match_list in grouped_matches.items():
            # The first match is the primary (highest priority)
            primary_match = match_list[0]
            
            # Add all alternative matches
            primary_match['alternative_matches'] = match_list[1:] if len(match_list) > 1 else []
            primary_match['total_matches'] = len(match_list)
            
            matches.append(primary_match)
        
        # Sort by combined_score and apply pagination
        matches.sort(key=lambda x: (x['combined_score'] or 0, x['created_at']), reverse=True)
        total = len(matches)
        matches = matches[offset:offset + limit]
        
        # For each match, the recommended_match is now in alternative_matches
        # No need to query separately, already included
        
        cursor.close()
        conn.close()
        
        return jsonify({
            'matches': matches,
            'total': total,
            'limit': limit,
            'offset': offset
        })
        
    except Exception as e:
        logger.error(f"Error fetching matches: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<product_a_id>/<store_b>/recommended')
def get_recommended_match(product_a_id, store_b):
    """
    Get recommended match for a specific (product_a_id, store_b) pair.
    
    Returns the highest-scoring match that is different from the currently validated match.
    If a perfect match exists, returns None (no recommendation needed).
    If a validated match exists, returns highest-scoring alternative if score is higher.
    """
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        
        # First, get the current validated/perfect match
        current_query = """
        SELECT 
            product_b_id,
            combined_score,
            validation_result,
            validated
        FROM product_match_validation
        WHERE product_a_id = %s 
        AND store_b = %s
        ORDER BY 
            CASE 
                WHEN validation_result = 'perfect' THEN 1
                WHEN validation_result IN ('correct', 'incorrect', 'uncertain') THEN 2
                ELSE 3
            END,
            created_at DESC
        LIMIT 1
        """
        
        cursor.execute(current_query, (product_a_id, store_b))
        current_match = cursor.fetchone()
        
        # If perfect match exists, no recommendation
        if current_match and current_match['validation_result'] == 'perfect':
            cursor.close()
            conn.close()
            return jsonify({
                'has_perfect_match': True,
                'recommended_match': None,
                'message': 'Perfect match already exists, no recommendation needed'
            })
        
        # Find highest scoring alternative
        if current_match:
            current_product_b = current_match['product_b_id']
            current_score = current_match['combined_score']
            
            # Get highest scoring match that is different from current
            rec_query = """
            SELECT 
                product_b_id,
                product_b_siid,
                product_b_name,
                product_b_description,
                product_b_url,
                combined_score,
                graph_score,
                name_similarity,
                description_similarity,
                euclidean_similarity,
                overlap_count,
                shared_nodes,
                created_at,
                validation_result
            FROM product_match_validation
            WHERE product_a_id = %s 
            AND store_b = %s
            AND product_b_id != %s
            ORDER BY combined_score DESC
            LIMIT 1
            """
            
            cursor.execute(rec_query, (product_a_id, store_b, current_product_b))
        else:
            # No current match, just get the highest scoring one
            rec_query = """
            SELECT 
                product_b_id,
                product_b_siid,
                product_b_name,
                product_b_description,
                product_b_url,
                combined_score,
                graph_score,
                name_similarity,
                description_similarity,
                euclidean_similarity,
                overlap_count,
                shared_nodes,
                created_at,
                validation_result
            FROM product_match_validation
            WHERE product_a_id = %s 
            AND store_b = %s
            ORDER BY combined_score DESC
            LIMIT 1
            """
            
            cursor.execute(rec_query, (product_a_id, store_b))
            current_score = 0.0
        
        recommended = cursor.fetchone()
        
        cursor.close()
        conn.close()
        
        # Only recommend if score is higher
        if recommended and recommended['combined_score'] > current_score:
            return jsonify({
                'has_perfect_match': False,
                'current_match': current_match,
                'recommended_match': recommended,
                'score_improvement': recommended['combined_score'] - current_score
            })
        else:
            return jsonify({
                'has_perfect_match': False,
                'current_match': current_match,
                'recommended_match': None,
                'message': 'No higher-scoring alternative found'
            })
        
    except Exception as e:
        logger.error(f"Error fetching recommended match: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/validate', methods=['POST'])
def validate_match():
    """
    Validate a match.
    
    Expected JSON body:
        {
            "id": 123,
            "validation_result": "correct|incorrect|uncertain|perfect",
            "notes": "Optional validation notes"
        }
    """
    data = request.get_json()
    logger.info(f"Received validation request: {data}")
    
    required_fields = ['id', 'validation_result']
    if not data or not all(field in data for field in required_fields):
        logger.error(f"Missing required fields. Data received: {data}")
        return jsonify({'error': f'Missing required fields: {required_fields}'}), 400
    
    match_id = data['id']
    validation_result = data['validation_result']
    notes = data.get('notes', '')
    
    # Validate validation_result
    if validation_result not in ['perfect', 'correct', 'incorrect', 'uncertain']:
        return jsonify({'error': 'Invalid validation_result'}), 400
    
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        
        update_query = """
        UPDATE product_match_validation
        SET 
            validated = TRUE,
            validation_result = %s,
            notes = %s
        WHERE id = %s
        """
        
        cursor.execute(update_query, (validation_result, notes, match_id))
        
        if cursor.rowcount == 0:
            cursor.close()
            conn.close()
            return jsonify({'error': 'Match not found'}), 404
        
        conn.commit()
        
        cursor.close()
        conn.close()
        
        logger.info(f"Match (id={match_id}) validated as '{validation_result}'")
        
        return jsonify({
            'success': True,
            'message': 'Validation saved successfully'
        })
        
    except Exception as e:
        logger.error(f"Error validating match: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/stats')
def get_stats():
    """Get validation statistics."""
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        
        stats_query = """
        SELECT 
            COUNT(*) as total_matches,
            COUNT(CASE WHEN validated = TRUE THEN 1 END) as validated_count,
            COUNT(CASE WHEN validated = FALSE OR validated IS NULL THEN 1 END) as pending_count,
            COUNT(CASE WHEN validation_result = 'perfect' THEN 1 END) as perfect_count,
            COUNT(CASE WHEN validation_result = 'correct' THEN 1 END) as correct_count,
            COUNT(CASE WHEN validation_result = 'incorrect' THEN 1 END) as incorrect_count,
            COUNT(CASE WHEN validation_result = 'uncertain' THEN 1 END) as uncertain_count,
            AVG(combined_score) as avg_combined_score,
            AVG(CASE WHEN validation_result = 'perfect' THEN combined_score END) as avg_score_perfect,
            AVG(CASE WHEN validation_result = 'correct' THEN combined_score END) as avg_score_correct,
            AVG(CASE WHEN validation_result = 'incorrect' THEN combined_score END) as avg_score_incorrect
        FROM product_match_validation
        """
        
        cursor.execute(stats_query)
        stats = cursor.fetchone()
        
        logger.info(f"Stats fetched: {stats}")
        
        # Get store pairs
        store_query = """
        SELECT DISTINCT store_a, store_b, COUNT(*) as count
        FROM product_match_validation
        GROUP BY store_a, store_b
        ORDER BY count DESC
        """
        
        cursor.execute(store_query)
        store_pairs = cursor.fetchall()
        
        cursor.close()
        conn.close()
        
        return jsonify({
            'stats': stats,
            'store_pairs': store_pairs
        })
        
    except Exception as e:
        logger.error(f"Error fetching stats: {e}")
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500

@app.route('/api/product_details')
def get_product_details():
    """
    Get detailed product information from Neo4j.
    
    Query parameters:
        - product_id: Product ID
        - store: Store name
    """
    product_id = request.args.get('product_id')
    store = request.args.get('store')
    
    if not product_id or not store:
        return jsonify({'error': 'Missing product_id or store'}), 400
    
    try:
        # This would require Neo4j connection - placeholder for now
        # You can implement this to fetch additional product details from Neo4j
        return jsonify({
            'product_id': product_id,
            'store': store,
            'message': 'Neo4j integration pending'
        })
        
    except Exception as e:
        logger.error(f"Error fetching product details: {e}")
        return jsonify({'error': str(e)}), 500


if __name__ == '__main__':
    import argparse
    
    parser = argparse.ArgumentParser(description='Product Match Validation Web Interface')
    parser.add_argument('--host', default='0.0.0.0', help='Host to bind to (default: 0.0.0.0)')
    parser.add_argument('--port', type=int, default=5011, help='Port to bind to (default: 5000)')
    parser.add_argument('--debug', action='store_true', help='Run in debug mode')
    
    args = parser.parse_args()
    
    logger.info("=" * 70)
    logger.info("  PRODUCT MATCH VALIDATION WEB INTERFACE")
    logger.info("=" * 70)
    logger.info(f"Starting server on http://{args.host}:{args.port}")
    logger.info("Press CTRL+C to stop")
    logger.info("=" * 70)
    
    app.run(host=args.host, port=args.port, debug=args.debug)
